---
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: dpb587/bosh-release-resource
  inputs:
  - name: release
  run:
    path: sh
    args:
    - -c
    - |
      set -euo pipefail

      cd release

      tar -xzf *.tgz
      tar -tzf packages/ssoca-clients.tgz | grep -- ssoca-clients/ssoca-client-
