---
name: ssoca
releases:
  - name: ssoca
    version: latest
  # https://github.com/dpb587/ssh-conf-bosh-release
  - name: ssh-conf
    version: latest
  # https://github.com/dpb587/openvpn-bosh-release
  - name: openvpn
    version: latest
instance_groups:
  - name: allinone
    jobs:
    - name: ssoca
      release: ssoca
      properties:
        env:
          name: "bosh-lite-allinone"
          title: "ssoca demo on bosh-lite"
          banner: "A BOSH release for ssoca"
          url: "https://ssoca.bosh-lite.com:18705"
          metadata:
            ca: ((ca.ca))
            ui.color: washed-green
            ui.link.GitHub Repository: https://github.com/dpb587/ssoca
            ui.link.User Documentation: https://dpb587.github.io/ssoca
        server:
          certificate: ((ssoca.certificate))
          private_key: ((ssoca.private_key))
        auth:
          type: ((ssoca_auth_type))
          options: ((ssoca_auth_options))
        certauths:
        - type: memory
          options:
            certificate: ((ca.certificate))
            private_key: ((ca.private_key))
        services:
        - type: ssh
          require:
          - authenticated: ~
          options:
            target:
              host: ssoca.bosh-lite.com
              user: vcap
        - type: openvpn
          require:
          - authenticated: ~
          options:
            profile: |
              client
              dev tun
              proto tcp
              remote ssoca.bosh-lite.com 443
              comp-lzo
              resolv-retry infinite
              nobind
              persist-key
              persist-tun
              mute-replay-warnings
              remote-cert-tls server
              verb 3
              mute 20
              tls-client
              cipher BF-CBC
              keysize 256
    - name: sshd_settings
      release: ssh-conf
      properties:
        disable_authorized_keys: true
        disable_password_authentication: true
        trusted_ca: ((ca.certificate))
    - name: openvpn
      release: openvpn
      properties:
        openvpn:
          ca_crt: ((ca.certificate))
          dh_pem: |
            -----BEGIN DH PARAMETERS-----
            MIIBCAKCAQEA/oih/YXvkf13npOIF5LW170/V5j4R20NjL/IzgdZUYMlsQtm5zMZ
            LwA8Vk1v9UnSWkopAGuJ8gZxz4qKk2p2MLzHSDwXC5khGrrJlHfjn7H0lYilyFqn
            2YhmfCQ7z7ih0jUS/iNf/+xUmfoJn/2OMEY3gmcAxAbtVRqNtGFwsTjtap3Rgbt9
            /j7Xbrsp3JqSeWN3VSqMzAgUrjkkkv52HcDo4zA1KfN7m+ROj/uGxcrmvZr7G0RK
            9yJ2f8I1x8EW3p+CmWhHcmoNyxxlfRHIsZ+82+BIessN99pSxCbjWvhggntFLRwC
            fcrq5wk9ei7dzYjZHSPHqvhmmZgWKJZYQwIBAg==
            -----END DH PARAMETERS-----
          iptables:
          - POSTROUTING -t nat -s 172.31.172.0/24 -d 10.244.0.0/16 -j MASQUERADE
          local: 0.0.0.0
          port: 443
          push_routes:
          - 10.244.0.0 255.255.0.0
          server: 172.31.172.0 255.255.255.0
          server_crt: ((openvpn.certificate))
          server_key: ((openvpn.private_key))
    instances: 1
    vm_type: default
    stemcell: default
    networks:
    - name: default
    azs:
    - z1
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
variables:
- name: ca
  options:
    is_ca: true
    common_name: ssoca
  type: certificate
- name: openvpn
  options:
    ca: ca
    common_name: ssoca.bosh-lite.com
    extended_key_usage:
    - server_auth
  type: certificate
- name: ssoca
  options:
    ca: ca
    common_name: ssoca.bosh-lite.com
    extended_key_usage:
    - server_auth
  type: certificate
