---
# bosh deploy --recreate src/bosh-lite-allinone/deployment.yml --vars-file tmp/allinone.ops.yml --vars-store tmp/allinone.vars.yml
name: ssoca
releases:
  - name: bpm
    version: "0.2.0"
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.2.0
    sha1: f2bd126b17b3591160f501d88d79ccf0aba1ae54
  - name: networking
    version: "9"
    url: http://bosh.io/d/github.com/cloudfoundry/networking-release?v=9
    sha1: 9b5f9d27917c3754e492470ac6c9af80d62963db
  - name: ssoca
    version: create
    url: file://.
    # url: https://github.com/dpb587/ssh-conf-bosh-release
  - name: ssh-conf
    version: latest
    # url: https://github.com/dpb587/ssh-conf-bosh-release
  - name: openvpn
    version: latest
    # url: https://github.com/dpb587/openvpn-bosh-release
instance_groups:
  - name: allinone
    jobs:
    - name: bpm
      release: bpm
    - name: ssoca
      release: ssoca
      properties:
        env:
          name: "bosh-lite-allinone"
          title: "ssoca demo on bosh-lite"
          banner: "A BOSH release for ssoca"
          url: "https://ssoca.bosh-lite.com:18705"
          metadata:
            ca: ((ca.ca))
            ui.color: washed-green
            ui.link.GitHub Repository: https://github.com/dpb587/ssoca
            ui.link.User Documentation: https://dpb587.github.io/ssoca
        server:
          certificate: ((ssoca.certificate))
          private_key: ((ssoca.private_key))
        auth:
          type: ((ssoca_auth_type))
          options: ((ssoca_auth_options))
        certauths:
        - name: default
          type: memory
          options:
            certificate: ((ca.certificate))
            private_key: ((ca.private_key))
        services:
        - type: ssh
          require:
          - authenticated: ~
          options:
            certauth: default
            principals:
            - vcap
            target:
              host: ssoca.bosh-lite.com
              user: vcap
    - name: sshd_settings
      release: ssh-conf
      properties:
        disable_authorized_keys: true
        disable_password_authentication: true
        trusted_ca: ((ca.certificate))
    - name: openvpn
      release: openvpn
      properties:
          dh_pem: |
            -----BEGIN DH PARAMETERS-----
            MIIBCAKCAQEA/oih/YXvkf13npOIF5LW170/V5j4R20NjL/IzgdZUYMlsQtm5zMZ
            LwA8Vk1v9UnSWkopAGuJ8gZxz4qKk2p2MLzHSDwXC5khGrrJlHfjn7H0lYilyFqn
            2YhmfCQ7z7ih0jUS/iNf/+xUmfoJn/2OMEY3gmcAxAbtVRqNtGFwsTjtap3Rgbt9
            /j7Xbrsp3JqSeWN3VSqMzAgUrjkkkv52HcDo4zA1KfN7m+ROj/uGxcrmvZr7G0RK
            9yJ2f8I1x8EW3p+CmWhHcmoNyxxlfRHIsZ+82+BIessN99pSxCbjWvhggntFLRwC
            fcrq5wk9ei7dzYjZHSPHqvhmmZgWKJZYQwIBAg==
            -----END DH PARAMETERS-----
          extra_configs:
          - script-security 2
          - tls-verify "/var/vcap/packages/ssoca-openvpn-verify/bin/tls-verify 2m"
          - tls-export-cert /var/vcap/data/ssoca-openvpn-verify/certs
          local: 0.0.0.0
          port: 443
          push_routes:
          - 10.244.0.0 255.255.0.0
          server: 172.31.172.0 255.255.255.0
          tls_server: ((openvpn))
    - name: ssoca-openvpn-verify
      release: ssoca
    - name: iptables
      release: networking
      properties:
        iptables:
          nat:
            POSTROUTING:
            - -s 172.31.172.0/24 -d 10.244.0.0/16 -j MASQUERADE
    instances: 1
    vm_type: default
    stemcell: default
    networks:
    - name: default
    azs:
    - z1
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
variables:
- name: ca
  options:
    is_ca: true
    common_name: ssoca
  type: certificate
- name: openvpn
  options:
    ca: ca
    common_name: ssoca.bosh-lite.com
    extended_key_usage:
    - server_auth
  type: certificate
- name: ssoca
  options:
    ca: ca
    common_name: ssoca.bosh-lite.com
    extended_key_usage:
    - server_auth
  type: certificate
